# Generated by Django 3.1.7 on 2021-03-24 22:13

from django.db import migrations, models
from random_id import random_id


class Migration(migrations.Migration):

    dependencies = [
        ('howler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default=random_id, max_length=14, primary_key=True, serialize=False),
        ),
    ]
